### PR TITLE
Updated logo and favicon with small design tweaks

### PR DESCRIPTION
**Pull request by stegrainer**

### CODE REVIEW

**Comment by jgarber623** [comment]
Thanks for the PR, @stegrainer! I'll give it a look this week.

**Comment by stegrainer** [comment]
No problem! Still working on NASA content, but figured I'd at least push up a revised logo and favicon. :)

**Comment by jgarber623** [comment]
@stegrainer Just carried over your design changes and made a couple modifications along the way (including using flexbox for the row/column pieces). It's looking great!

https://spaceholder.cc/

**Comment by stegrainer** [comment]
Cool, thanks! I was on the fence about whether to go with flexbox or floats. Wasn't sure how far back you'd want to support. ;)

**Pull request closed without merging**
